"""empty message

Revision ID: 24673b5d6c14
Revises: 
Create Date: 2021-10-02 08:36:51.613705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24673b5d6c14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nidn', sa.String(length=20), nullable=False),
    sa.Column('niy', sa.String(length=20), nullable=False),
    sa.Column('load_name', sa.String(length=100), nullable=False),
    sa.Column('gs_id', sa.String(length=20), nullable=False),
    sa.Column('is_scraped', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrapped',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrapped_name', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('data_load_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_load_id'], ['data_load.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrapped')
    op.drop_table('data_load')
    # ### end Alembic commands ###
