"""empty message

Revision ID: a69ea70d5e67
Revises: 
Create Date: 2021-09-26 22:33:29.237307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69ea70d5e67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nidn', sa.String(length=20), nullable=False),
    sa.Column('niy', sa.String(length=20), nullable=False),
    sa.Column('load_name', sa.String(length=50), nullable=False),
    sa.Column('gs_id', sa.String(length=20), nullable=False),
    sa.Column('scraped', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_load')
    # ### end Alembic commands ###
